### ISSUE TITLE
Create a script for adding instances with given a number with randomized names

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#102]
The basic requirement:
* Start 3 PS instances -> it is already done by pmm-framework.sh
* Add 3 PS instances into pmm n given time, by changing the instance names(randomized)
* Best to do this with multi-threaded run

**Comment by ShahriyarR** [comment]
Syntax error:

```
$ python ~/percona-qa/pmm-tests/randomized_instances.py 
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 18, in <module>
    call_pmm_framework(ps,2)
NameError: name 'ps' is not defined
```

**Comment by ShahriyarR** [comment]
```
$ python ~/percona-qa/pmm-tests/randomized_instances.py 
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_1.sock af5d0aed-4806-499e-809c-6525cd4f4735
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 61, in <module>
    runner(100)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 57, in runner
    for i in range(i_count)]
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 47, in adding_instances
    process = subprocess.Popen(
NameError: global name 'subprocess' is not defined
```

**Comment by ShahriyarR** [comment]
After running in multi-threaded script, it seems to be pmm-admin is not thread-safe.
As it is picking up next port each time there are issues with this. Will update script to specify port while adding instances to overcome this problem and to improve further.

[multi_thread_run.txt](https://github.com/Percona-QA/percona-qa/files/1076988/multi_thread_run.txt)

**Comment by ShahriyarR** [comment]
The result for now:

```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --instance_type ps --instance_count 2 --pmm_instance_count 2
Shutting down mysql instance (--socket=/tmp/PS_NODE_1.sock)
Shutting down mysql instance (--socket=/tmp/PS_NODE_1.sock)
/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/tmp/PS_NODE_1.sock' (2)'
Check that mysqld is running and that the socket: '/tmp/PS_NODE_1.sock' exists!
Shutting down mysql instance (--socket=/tmp/PS_NODE_1.sock)
/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/tmp/PS_NODE_1.sock' (2)'
Check that mysqld is running and that the socket: '/tmp/PS_NODE_1.sock' exists!
Removing all local pmm client instances
User 'admin' is already present in MySQL server. Please create Orchestrator user manually.
[linux:metrics] OK, now monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_1.sock)
User 'admin' is already present in MySQL server. Please create Orchestrator user manually.
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_1.sock --service-port=19341 79faac4c-78b4-45d8-a530-ee3b9193cfc4 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_1.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_1.sock --service-port=41434 8949172c-4629-4306-9190-f8fb9abb500a 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_1.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_2.sock --service-port=32695 8998db09-fa20-4a6c-95d6-101f4debf34f 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_2.sock --service-port=45579 56873e07-442e-4dd0-8a85-b8a44b67617b 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_2.sock)
```

**Comment by ShahriyarR** [comment]
```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --help
Usage: randomized_instances.py [OPTIONS]

Options:
  --version                     Version information.
  --threads INTEGER             Give non-zero number to enable multi-thread
                                run!
  --instance_type TEXT          Passing instance type(ps, ms, md, pxc, mo) to
                                pmm-framework.sh  [required]
  --instance_count INTEGER      How many physical instances you want to start?
                                (Passing to pmm-framework.sh)  [required]
  --pmm_instance_count INTEGER  How many pmm instances you want to add with
                                randomized names from each physical instance?
                                (Passing to pmm-admin)  [required]
  --help                        Show this message and exit.
```

**Comment by ShahriyarR** [comment]
So now It is working and can be merged.
I could add several thousands of instances as a result:
```
$ sudo pmm-admin rm --all
OK, 3480 services were removed.
```
