### ISSUE TITLE
stress test -> openning 20000 client connections to instances

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#105]
The pmm-framework.sh will start PS instances by default with --max-connections=30000.
Then we can use sysbench to open-up 20K threads or mysqlslap with --concurrency.

**Comment by ShahriyarR** [comment]
It seems to be sysbench is not needed here, because it requires to run some SQL statements, for this ticket, it is valuable to connect to MySQL instance, maybe with sleep() for keeping high total connections.

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 244, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 240, in run_all
    create_sleep_query(create_sleep_queries, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 155, in create_sleep_query
    new_command = bash_command.format(dname, i_type, table_count)
NameError: global name 'table_count' is not defined
```

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 244, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 240, in run_all
    create_sleep_query(create_sleep_queries, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 161, in create_sleep_query
    stderr=None)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by ShahriyarR** [comment]
The overall script is working but it seems to be buggy, because it is waiting for each sleep() query to finish then proceed:

```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --instance_type ps --instance_count 2 --pmm_instance_count 0 --create_sleep_queries 20
Shutting down mysql instance (--socket=/tmp/PS_NODE_1.sock)
Shutting down mysql instance (--socket=/tmp/PS_NODE_2.sock)
Removing all local pmm client instances
User 'admin' is already present in MySQL server. Please create Orchestrator user manually.
[linux:metrics] OK, now monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_1.sock)
User 'admin' is already present in MySQL server. Please create Orchestrator user manually.
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Creating sleep() queries using MYSQL_SOCK=/tmp/PS_NODE_1.sock
^C
Aborted!
^C -- query aborted
+-----------------+
| sleep(10000000) |
+-----------------+
+-----------------+
```

Can be fixed by calling bash file in multi-thread manner or using Python/Connector to directly connect to MySQL instances.
