### ISSUE TITLE
stress test -> Large number of tables  (100000)

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#106]
The script should create 100000 tables if you pass some option.

**Comment by ShahriyarR** [comment]
```
]$ python ~/percona-qa/pmm-tests/randomized_instances.py --instance_type ps --instance_count 2 --pmm_instance_count 0 --create_databases 100 --create_tables 100
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 205, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: run_all() got an unexpected keyword argument 'create_tables'
```

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 205, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 201, in run_all
    create_table(create_tables, instance_type)
NameError: global name 'create_table' is not defined
```

**Comment by ShahriyarR** [comment]
Another syntax issue:
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 205, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 201, in run_all
    create_table(create_tables, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 123, in create_table
    new_command = bash_command.format(dname, i_type, db_count)
NameError: global name 'db_count' is not defined
```

**Comment by ShahriyarR** [comment]
Again permission denied issue:
Seems it needs chmod u+x for create_table.sh
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 205, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 201, in run_all
    create_table(create_tables, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 129, in create_table
    stderr=None)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by ShahriyarR** [comment]
The final fresh run:

```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --instance_type ps --instance_count 2 --pmm_instance_count 0 --create_databases 100 --create_tables 100
Shutting down mysql instance (--socket=/tmp/PS_NODE_1.sock)
Shutting down mysql instance (--socket=/tmp/PS_NODE_2.sock)
Removing all local pmm client instances
Orchestrator username :  admin
Orchestrator password :  passw0rd
[linux:metrics] OK, now monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_1.sock)
Orchestrator username :  admin
Orchestrator password :  passw0rd
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Creating databases using MYSQL_SOCK=/tmp/PS_NODE_1.sock
Creating databases using MYSQL_SOCK=/tmp/PS_NODE_2.sock
Creating tables using MYSQL_SOCK=/tmp/PS_NODE_1.sock
Creating tables using MYSQL_SOCK=/tmp/PS_NODE_2.sock
```
