### ISSUE TITLE
stress test -> Large number of databases (100000)

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#107]
The script should create N number (100000) of databases if you pass some option.

**Comment by ShahriyarR** [comment]
```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --help
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 121
    for i range(db_count):
              ^
SyntaxError: invalid syntax
```

**Comment by ShahriyarR** [comment]
```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --instance_type ps --instance_count 2 --pmm_instance_count 2 --create_databases 100
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 197, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: run_all() got an unexpected keyword argument 'create_databases'
```

**Comment by ShahriyarR** [comment]
Failed with:

```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --instance_type ps --instance_count 2 --pmm_instance_count 2 --create_databases 100
No services under pmm monitoring
WARNING! Another mysqld process using /tmp/PS_NODE_1.sock
[linux:metrics] OK, now monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_1.sock)
WARNING! Another mysqld process using /tmp/PS_NODE_2.sock
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_1.sock --service-port=37329 c6b8552d-708a-4687-8137-8548d90bdf0e 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_1.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_1.sock --service-port=53901 71cfd71a-5ad1-4996-b102-1cabbe53d340 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_1.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_2.sock --service-port=40809 930a53ce-a823-47e7-890b-c1b7911ba623 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Running -> sudo pmm-admin add mysql --user=root --socket=/tmp/PS_NODE_2.sock --service-port=36568 d7942e00-305d-4311-aff4-c2adaf31fca7 
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from slowlog using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 197, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 193, in run_all
    create_db(create_databases, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 114, in create_db
    new_command = bash_command.format(i_type)
KeyError: 'CLIENT_NAME'
```

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 197, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 193, in run_all
    create_db(create_databases, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 115, in create_db
    process = subprocess.Popen(new_command.split(), stdout=subprocess.PIPE)
NameError: global name 'subprocess' is not defined
```

**Comment by ShahriyarR** [comment]
Failed with:

```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 197, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 193, in run_all
    create_db(create_databases, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 115, in create_db
    process = Popen(split(new_command), stdout=PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 176, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 172, in run_all
    create_db(create_databases, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 105, in create_db
    new_command = bash_command.format(i_type, db_count)
IndexError: tuple index out of range
```

**Comment by ShahriyarR** [comment]
Another weird fail:

```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 182, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 178, in run_all
    create_db(create_databases, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 111, in create_db
    stderr=None)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 182, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 178, in run_all
    create_db(create_databases, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 111, in create_db
    stderr=None)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

**Comment by ShahriyarR** [comment]
The final result:

```
$ python ~/percona-qa/pmm-tests/randomized_instances.py --instance_type ps --instance_count 2 --pmm_instance_count 0 --create_databases 100
Shutting down mysql instance (--socket=/tmp/PS_NODE_1.sock)
Shutting down mysql instance (--socket=/tmp/PS_NODE_2.sock)
Removing all local pmm client instances
Orchestrator username :  admin
Orchestrator password :  passw0rd
[linux:metrics] OK, now monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_1.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_1.sock)
Orchestrator username :  admin
Orchestrator password :  passw0rd
[linux:metrics] OK, already monitoring this system.
[mysql:metrics] OK, now monitoring MySQL metrics using DSN root:***@unix(/tmp/PS_NODE_2.sock)
[mysql:queries] OK, now monitoring MySQL queries from perfschema using DSN root:***@unix(/tmp/PS_NODE_2.sock)
Creating databases using MYSQL_SOCK=/tmp/PS_NODE_1.sock
Creating databases using MYSQL_SOCK=/tmp/PS_NODE_2.sock
```
