### ISSUE TITLE
Wrong backup calculation percentage

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#11]
Result of run:

```
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-31-48/mysql_data_dir/server-cert.pem
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-31-48/mysql_data_dir/server-key.pem
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-31-48/mysql_data_dir/ca.pem
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-31-48/mysql_data_dir/ca-key.pem
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-31-48/mysql_data_dir/auto.cnf
Backup completed 399 %
```

**Comment by ShahriyarR** [comment]
Result after commit:

```
# /opt/Python-3.3.2/bin/tokubackup --backup
mysql: [Warning] Using a password on the command line interface can be insecure.
Something went wrong: [Errno 17] File exists: '/var/lib/tokubackupdir/2017-01-12_12-43-43'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/Python-3.3.2/lib/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 159, in on_created
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 147, in final_calculation
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 116, in calculate_progress
ValueError: could not convert string to float: 'du: cannot access ‘None’: No such file or directory'
```

**Comment by ShahriyarR** [comment]
Result of fix:

```
# /opt/Python-3.3.2/bin/tokubackup --backup
Backup will bo stored in  /var/lib/tokubackupdir/2017-01-12_12-53-40
mysql: [Warning] Using a password on the command line interface can be insecure.
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-53-40/mysql_data_dir
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-53-40/mysql_data_dir/mysql
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-53-40/mysql_data_dir/sys
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-53-40/mysql_data_dir/performance_schema
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-53-40/mysql_data_dir/ibdata1
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-53-40/mysql_data_dir/ib_logfile0
Created file in backup directory -> /var/lib/tokubackupdir/2017-01-12_12-53-40/mysql_data_dir/ib_logfile1
Backup completed 100 %
```
