### ISSUE TITLE
Fix for multithreaded stress test run for pmm; use the value from --threads option

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#114]
There is a bug in:

```
def runner(pmm_count, i_name, i_count, threads=0):
    """
    Main runner function; using Threading;
    """
    pmm_framework_wipe_client()
    pmm_framework_add_client(i_name, i_count)
    sockets = getting_instance_socket()
    for sock in sockets:
        if threads > 0:
            # Enabling Threads
            # Worker count is going to be equal to passed pmm_count
            workers = [threading.Thread(target=adding_instances(sock, threads), name="thread_"+str(i))
                        for i in range(pmm_count)]
            [worker.start() for worker in workers]
            [worker.join() for worker in workers]
        elif threads == 0:
            for i in range(pmm_count):
                adding_instances(sock, threads)
    return 1
```
It is using range(pmm_count) rather than range(threads)

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 214, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 206, in run_all
    runner(pmm_instance_count, instance_type, instance_count, threads)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 96, in runner
    for i in range(count)]
TypeError: range() integer end argument expected, got float
```
