### ISSUE TITLE
stress test -> Large number of distinct queries (different digest) ran every minute 100000

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#119]
I am going to use mysqlslap for this task because it is much more suitable:

https://dev.mysql.com/doc/refman/5.7/en/mysqlslap.html

For eg:
Supply your own create and query SQL statements, with 50 clients querying and 200 selects for each (enter the command on a single line):
```
mysqlslap --delimiter=";"
  --create="CREATE TABLE a (b int);INSERT INTO a VALUES (23)"
  --query="SELECT * FROM a" --concurrency=50 --iterations=200
```
Let mysqlslap build the query SQL statement with a table of two INT columns and three VARCHAR columns. Use five clients querying 20 times each.

```
mysqlslap --concurrency=5 --iterations=20
  --number-int-cols=2 --number-char-cols=3
  --auto-generate-sql
```

**Comment by ShahriyarR** [comment]
```
mysqlslap --concurrency=200 --iterations=20 --number-int-cols=2 --number-char-cols=3 --auto-generate-sql --socket=/tmp/mysql_sandbox5718.sock --port=5718 --user=msandbox --password=msandbox --auto-generate-sql-unique-query-number=2000 --auto-generate-sql-execute-number=2000 --auto-generate-sql-write-number=2000 --auto-generate-sql-unique-write-number=2000
```

Executing 2000 unique insert and select with 200 client 20 times.

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 268, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 264, in run_all
    create_unique_query(create_unique_queries, instance_type)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/randomized_instances.py", line 178, in create_unique_query
    stderr=None)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by ShahriyarR** [comment]
```
$ MYSQL_SOCK=/tmp/PS_NODE_1.sock
Benchmark
	Average number of seconds to run all queries: 4.179 seconds
	Minimum number of seconds to run all queries: 3.425 seconds
	Maximum number of seconds to run all queries: 5.698 seconds
	Number of clients running queries: 200
	Average number of queries per client: 20

MYSQL_SOCK=/tmp/PS_NODE_2.sock
Benchmark
	Average number of seconds to run all queries: 3.489 seconds
	Minimum number of seconds to run all queries: 2.902 seconds
	Maximum number of seconds to run all queries: 4.894 seconds
	Number of clients running queries: 200
	Average number of queries per client: 20
```

**Comment by ShahriyarR** [comment]
```
/home/shahriyar.rzaev/percona-qa/pmm-tests/create_unique_queries.sh: line 33: syntax error near unexpected token `done'
/home/shahriyar.rzaev/percona-qa/pmm-tests/create_unique_queries.sh: line 33: `done'
```

**Comment by ShahriyarR** [comment]
Full result:

```
$ MYSQL_SOCK=/tmp/PS_NODE_1.sock
Benchmark
	Average number of seconds to run all queries: 7.365 seconds
	Minimum number of seconds to run all queries: 7.365 seconds
	Maximum number of seconds to run all queries: 7.365 seconds
	Number of clients running queries: 1
	Average number of queries per client: 200

MYSQL_SOCK=/tmp/PS_NODE_2.sock
Benchmark
	Average number of seconds to run all queries: 4.742 seconds
	Minimum number of seconds to run all queries: 4.742 seconds
	Maximum number of seconds to run all queries: 4.742 seconds
	Number of clients running queries: 1
	Average number of queries per client: 200
```
