### ISSUE TITLE
stress test -> implement inserting longtext data for pmm stress test

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#126]
As part of Limits/Exceptions project.
It is good idea to insert relatively large data into table i.e LONGTEXT should be supported.

**Comment by ShahriyarR** [comment]
```
$ time python ~/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py --instance_type ps --instance_count 25 --pmm_instance_count 0
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py", line 364, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: run_all() got an unexpected keyword argument 'insert_longtexts'

real	0m0.189s
user	0m0.055s
sys	0m0.009s
```
