### ISSUE TITLE
Add "SHOW GLOBAL VARIABLES" and "SHOW SESSION VARIABLES" output into backup directory

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#13]
Based on discussion here:
https://tokutek.atlassian.net/browse/BACKUP-119

It is valuable to store the result of this statements as separate files in backup directory.

**Comment by ShahriyarR** [comment]
First run result:

```
# /opt/Python-3.3.2/bin/tokubackup --backup
Traceback (most recent call last):
  File "/opt/Python-3.3.2/bin/tokubackup", line 9, in <module>
    load_entry_point('mysql-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/tokubackup.py", line 24, in all_procedure
  File "/opt/Python-3.3.2/lib/python3.3/runpy.py", line 178, in run_module
    fname, loader, pkg_name)
  File "/opt/Python-3.3.2/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 253, in <module>
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 165, in __init__
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 48, in get_tokudb_variable_value
TypeError: 'MySQLCursor' object is not callable
```

**Comment by ShahriyarR** [comment]
New run:
```
# /opt/Python-3.3.2/bin/tokubackup --backup
Backup will be stored in  /var/lib/tokubackupdir/2017-01-12_15-51-56
mysql: [Warning] Using a password on the command line interface can be insecure.
Something went wrong in create_mysql_variables_info(): must be str, not tuple
```

**Comment by ShahriyarR** [comment]
Another problem is for missing newline:

```
auto_generate_certs==>ONauto_increment_increment==>1auto_increment_offset==>1autocommit==>ONautomatic_sp_privileges==>ONavoid_temporal_upgrade==>OFFback_log==>80basedir==>/usr/big_tables==>OFFbind_address==>*binlog_cache_size==>32768binlog_checksum==>CRC32binlog_direct_non_transactional_updates==>OFFbinlog_error_action==>ABORT_SERVERbinlog_format==>ROWbinlog_group_commit_sync_delay==>0binlog_group_commit_sync_no_delay_count==>0binlog_gtid_simple_recovery==>ONbinlog_max_flush_queue_time==>0binlog_order_commits==>ONbinlog_row_image==>FULLbinlog_rows_query_log_events==>OFFbinlog_stmt_cache_size==>32768block_encryption_mode==>aes-128-ecbbulk_insert_buffer_size==>8388608character_set_client==>latin1character_set_connection==>latin1character_set_database
```
