### ISSUE TITLE
Creating sleep() queries consumed too much resources

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#131]
It is convenient to move this functionality from bash to python.
Should figure out the proper way.

**Comment by ShahriyarR** [comment]
```
>           cursor.close()
E           UnboundLocalError: local variable 'cursor' referenced before assignment

../percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py:195: UnboundLocalError
------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------
Unsupported argument 'socket'
```

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py", line 397, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py", line 387, in run_all
    run_sleep_query(create_sleep_queries)
TypeError: run_sleep_query() takes at least 2 arguments (1 given)
```

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py", line 397, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py", line 387, in run_all
    run_sleep_query('%d %s %d' % create_sleep_queries)
TypeError: %d format: a number is required, not unicode
```

**Comment by ShahriyarR** [comment]
Passed all tests:

```
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_pmm_framework_add_client PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_getting_instance_socket PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_adding_instances PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_create_db PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_create_table PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_run_sleep_query PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_create_unique_query PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_insert_blob PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_insert_longtext PASSED
../percona-qa/pmm-tests/pmm_stress_test_py_tests/test_module01.py::TestPMMStress::test_pmm_framework_wipe_client PASSED
```
