### ISSUE TITLE
Call PyTests from bats

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#177]
Create bats file for running pytests.

**Comment by ShahriyarR** [comment]
```
not ok 1 Running test_check_if_collection_exists
# (in test file /home/shahriyar.rzaev/percona-qa/myrocks-tests/pytests.bats, line 10)
#   `[ $status -eq 0 ]' failed
# ============================= test session starts ============================== platform linux2 -- Python 2.7.5, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python cachedir: .cache rootdir: /home/shahriyar.rzaev/MYROCKS/PS250817-percona-server-5.7.19-17-linux-x86_64-debug, inifile: collecting ... ========================= no tests ran in 0.00 seconds ========================= ERROR: file not found: /usr/local/libexec/myrocks_mysqlx_plugin_test/test_module01.py::TestXPlugin::test_check_if_collection_exists
```

**Comment by ShahriyarR** [comment]
Failed with:

```
#Running X Plugin tests#
 ✓ Running test_check_if_collection_exists
 ✗ Running test_check_collection_count
   (in test file /home/shahriyar.rzaev/percona-qa/myrocks-tests/pytests.bats, line 16)
     `[ $status -eq 0 ]' failed
   Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 379, in _importconftest mod = conftestpath.pyimport() File "/usr/lib/python2.7/site-packages/py/_path/local.py", line 662, in pyimport __import__(modname) File "/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module py.builtin.exec_(co, mod.__dict__) File "/usr/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_ exec2(obj, globals, locals) File "<string>", line 7, in exec2 File "/home/shahriyar.rzaev/percona-qa/myrocks-tests/myrocks_mysqlx_plugin_test/conftest.py", line 5, in <module> plugin_obj = MyXPlugin("generated_columns_test", "my_collection") File "/home/shahriyar.rzaev/percona-qa/myrocks-tests/myrocks_mysqlx_plugin/myrocks_mysqlx_plugin.py", line 24, in __init__ self.schema.create_collection(self.collection_name) File "/usr/lib64/python2.7/site-packages/mysqlx/crud.py", line 267, in create_collection raise ProgrammingError("Collection already exists") ProgrammingError: Collection already exists ERROR: could not load /home/shahriyar.rzaev/percona-qa/myrocks-tests/myrocks_mysqlx_plugin_test/conftest.py
```

**Comment by ShahriyarR** [comment]
The failed API function:

```
def create_collection(self, name, reuse=False):
        """Creates in the current schema a new collection with the specified
        name and retrieves an object representing the new collection created.

        Args:
            name (str): The name of the collection.
            reuse (bool): `True` to reuse an existing collection.

        Returns:
            mysqlx.Collection: Collection object.

        Raises:
            ProgrammingError: If ``reuse`` is False and collection exists.
        """
        if not name:
            raise ProgrammingError("Collection name is invalid")
        collection = Collection(self, name)
        if not collection.exists_in_database():
            self._connection.execute_nonquery("xplugin", "create_collection",
                                              True, self._name, name)
        elif not reuse:
            raise ProgrammingError("Collection already exists")
        return collection
```

**Comment by ShahriyarR** [comment]
Fixed the error handling:

```
def _read_message(self, rs):
        while True:
            msg = self._reader.read_message()
            if msg.type == "Mysqlx.Error":
>               raise OperationalError(msg["msg"])
E               OperationalError: The JSON binary value contains invalid data.

/usr/lib64/python2.7/site-packages/mysqlx/protocol.py:301: OperationalError
```

**Comment by ShahriyarR** [comment]
The final run:

```
$ clone=0 tap=0 bash  ~/percona-qa/myrocks-tests/myrocks-testsuite.sh
Skipping Clone and Build
Running startup.sh from percona-qa
Adding scripts: start | start_group_replication | start_valgrind | start_gypsy | stop | kill | setup | cl | test | init | wipe | all | prepare | run | measure | myrocks_tokudb_init
Setting up server with default directories
2017-08-25T13:37:37.263907Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-25T13:37:38.508926Z 0 [Warning] InnoDB: New log files created, LSN=45790
2017-08-25T13:37:38.990588Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2017-08-25T13:37:39.238217Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 90062c03-899a-11e7-ab80-002590e9b448.
2017-08-25T13:37:39.261483Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2017-08-25T13:37:39.516377Z 0 [Warning] CA certificate ca.pem is self signed.
2017-08-25T13:37:39.654756Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
Enabling additional TokuDB/ROCKSDB engine plugin items if exists
Server socket: /home/shahriyar.rzaev/MYROCKS/PS250817-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock with datadir: /home/shahriyar.rzaev/MYROCKS/PS250817-percona-server-5.7.19-17-linux-x86_64-debug/data
Server on socket /home/shahriyar.rzaev/MYROCKS/PS250817-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock with datadir /home/shahriyar.rzaev/MYROCKS/PS250817-percona-server-5.7.19-17-linux-x86_64-debug/data halted
Done! To get a fresh instance at any time, execute: ./all (executes: stop;wipe;start;sleep 5;cl)
Starting Server!
Server socket: /home/shahriyar.rzaev/MYROCKS/PS250817-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock with datadir: /home/shahriyar.rzaev/MYROCKS/PS250817-percona-server-5.7.19-17-linux-x86_64-debug/data
Creating sample database
Creating sample table
Altering table engine
Running generated_columns.bats
 ✓ Adding virtual generated json type column
 ✓ Adding stored generated json type column
 ✓ Adding stored generated varchar type column

3 tests, 0 failures
Running json.bats
 ✓ Adding json column

1 test, 0 failures
Installing mysql-connector-python
Already Installed
Installing mysqlx plugin
Creating sample user
Granting sample user
#Running X Plugin tests#
 ✓ Running test_check_if_collection_exists
 ✓ Running test_check_collection_count
 ✓ Running test_alter_table_engine_raises
 ✓ Running test_alter_table_drop_column
 ✓ Running test_alter_table_engine
 ✓ Running test_check_if_table_exists
 ✓ Running test_check_table_count
 ✓ Running test_check_table_name
 ✓ Running test_check_schema_name
 ✓ Running test_check_if_table_is_view
 ✓ Running test_create_view_from_collection
 ✓ Running test_select_from_table
 ✓ Running test_select_from_view

13 tests, 0 failures
```
