### ISSUE TITLE
create_sleep_query.sh failed with PXC

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#205]
```
ls: cannot access ?ercona-?erver-5.*: No such file or directory
Creating sleep() queries using MYSQL_SOCK=/tmp/PXC_NODE_3.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests//create_sleep_queries.sh: line 23: /home/shahriyar.rzaev/PXC_servers//bin/mysql: No such file or directory
ls: cannot access ?ercona-?erver-5.*: No such file or directory
Creating sleep() queries using MYSQL_SOCK=/tmp/PXC_NODE_3.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests//create_sleep_queries.sh: line 23: /home/shahriyar.rzaev/PXC_servers//bin/mysql: No such file or directory
ls: ls: cannot access ?ercona-?erver-5.*: No such file or directory
Creating sleep() queries using MYSQL_SOCK=/tmp/PXC_NODE_3.sock
cannot access ?ercona-?erver-5.*: No such file or directory
/home/shahriyar.rzaev/percona-qa/pmm-tests//create_sleep_queries.sh: line 23: /home/shahriyar.rzaev/PXC_servers//bin/mysql: No such file or directory
Creating sleep() queries using MYSQL_SOCK=/tmp/PXC_NODE_3.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests//create_sleep_queries.sh: line 23: /home/shahriyar.rzaev/PXC_servers//bin/mysql: No such file or directory
ls: cannot access ?ercona-?erver-5.*: No such file or directory
Creating sleep() queries using MYSQL_SOCK=/tmp/PXC_NODE_3.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests//create_sleep_queries.sh: line 23: /home/shahriyar.rzaev/PXC_servers//bin/mysql: No such file or directory
ls: cannot access ?ercona-?erver-5.*: No such file or directory
ls: cannot access ?ercona-?erver-5.*: No such file or directory
Creating sleep() queries using MYSQL_SOCK=/tmp/PXC_NODE_3.sock
```

**Comment by ShahriyarR** [comment]
It seems to be that wrong instance type passed to function:

```
/home/shahriyar.rzaev/percona-qa/pmm-tests/create_sleep_queries.sh ps 20 /tmp/PXC_NODE_1.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests/create_sleep_queries.sh ps 20 /tmp/PXC_NODE_1.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests/create_sleep_queries.sh ps 20 /tmp/PXC_NODE_1.sock
ls: cannot access ?ercona-?erver-5.*: No such file or directory
Creating sleep() queries using MYSQL_SOCK=/tmp/PXC_NODE_1.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests/create_sleep_queries.sh ps 20 /tmp/PXC_NODE_1.sock
/home/shahriyar.rzaev/percona-qa/pmm-tests/create_sleep_queries.sh: line 23: /home/shahriyar.rzaev/PXC_servers//bin/mysql: No such file or directory
```

So instead of pxc the ps passed

**Comment by ShahriyarR** [comment]
It seems to be I have a buggy function here which is accepting not the passed instance type.

**Comment by ShahriyarR** [comment]
Failed with:
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py", line 459, in <module>
    run_all()
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/py_2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/percona-qa/pmm-tests/pmm_stress_test_py/randomized_instances.py", line 446, in run_all
    run_sleep_query(int(create_sleep_queries[0]), instance_type, int(create_sleep_queries[2]))
IndexError: tuple index out of range
```

**Comment by ShahriyarR** [comment]
Can be considered as fixed.
