### ISSUE TITLE
AutoTokubackup failed with "AttributeError: 'CheckMySQLEnvironment' object has no attribute 'user'"

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#35]
With Python 3.3.2 there is no such issue but with Python 3.5.3 the result is:

```
[root@tokubackup AutoTokuBackup]# /opt/Python-3.5.3/bin/tokubackup --backup
Traceback (most recent call last):
  File "/opt/Python-3.5.3/bin/tokubackup", line 11, in <module>
    load_entry_point('mysql-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/tokubackup.py", line 24, in all_procedure
  File "/opt/Python-3.5.3/lib/python3.5/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/opt/Python-3.5.3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/backup/backup_calculation.py", line 258, in <module>
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/backup/backup_calculation.py", line 26, in __init__
AttributeError: 'CheckMySQLEnvironment' object has no attribute 'user'
Exception ignored in: <bound method CheckMySQLEnvironment.__del__ of <__main__.CheckMySQLEnvironment object at 0x7ff972097d30>>
Traceback (most recent call last):
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/backup/backup_calculation.py", line 32, in __del__
AttributeError: 'CheckMySQLEnvironment' object has no attribute 'cursor'
```

**Comment by ShahriyarR** [comment]
Another fail in run_backup() function:

```
[root@tokubackup AutoTokuBackup]# /opt/Python-3.5.3/bin/tokubackup --backup
Backup will be stored in  /home/backup_dir/2017-01-30_13-52-29
Something went wrong in run_backup(): 'CheckMySQLEnvironment' object has no attribute 'user'
```

**Comment by ShahriyarR** [comment]
Seems to be worked now. Closing
