### ISSUE TITLE
Implement copying original my.cnf to backup directory

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#37]
Originally described here:

https://tokutek.atlassian.net/browse/BACKUP-119

So the general idea is that, for keeping informed what was the server options during backup, the original configuration file should be kept.

**Comment by ShahriyarR** [comment]
Failed with:

```
[root@tokubackup AutoTokuBackup]# tokubackup --backup
Backup will be stored in  /var/lib/tokubackupdir/2017-01-30_20-44-36
Running backup command => /home/sh/percona-server/5.7.16/bin/mysql -uroot --password=msandbox --host=localhost --socket=/tmp/mysql_sandbox5716.sock -e set tokudb_backup_dir='/var/lib/tokubackupdir/2017-01-30_20-44-36'
mysql: [Warning] Using a password on the command line interface can be insecure.
Traceback (most recent call last):
  File "/home/virtualenvs/py3_5_3_tokubackup/bin/tokubackup", line 11, in <module>
    load_entry_point('mysql-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/tokubackup.py", line 24, in all_procedure
  File "/opt/Python-3.5.3/lib/python3.5/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/opt/Python-3.5.3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/backup/backup_calculation.py", line 304, in <module>
AttributeError: 'CheckMySQLEnvironment' object has no attribute 'mysql_defaults_file'
```
