### ISSUE TITLE
Remove backup calculation and stop the watchdog observer after finishing backup

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#39]
The problem is the watchdog process for observing backup directory did not exiting properly.
It requiring keyboard interrupt. But this is not suitable.

**Comment by ShahriyarR** [comment]
```
[root@tokubackup AutoTokuBackup]# tokubackup --backup
Backup will be stored in  /var/lib/tokubackupdir/2017-01-31_12-01-00
Running backup command => /home/sh/percona-server/5.7.16/bin/mysql -uroot --password=msandbox --host=localhost --socket=/tmp/mysql_sandbox5716.sock -e set tokudb_backup_dir='/var/lib/tokubackupdir/2017-01-31_12-01-00'
mysql: [Warning] Using a password on the command line interface can be insecure.
Traceback (most recent call last):
  File "/home/virtualenvs/py3_5_3_tokubackup/bin/tokubackup", line 11, in <module>
    load_entry_point('mysql-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/tokubackup.py", line 24, in all_procedure
  File "/opt/Python-3.5.3/lib/python3.5/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/opt/Python-3.5.3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/backup/backup_calculation.py", line 325, in <module>
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/backup/backup_calculation.py", line 301, in main
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/mysql_autotokubackup-1.0-py3.5.egg/backup/backup_calculation.py", line 90, in create_mysql_variables_info
NameError: name 'backupdir' is not defined
```
