### ISSUE TITLE
AttributeError: 'CheckMySQLEnvironment' object has no attribute 'backupdir'

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#5]
AutoTokubackup run failed with:

```
[root@tokubackup ~]# /opt/Python-3.3.2/bin/tokubackup --backup
Missing config file : /etc/tokubackup.conf
Traceback (most recent call last):
  File "/opt/Python-3.3.2/bin/tokubackup", line 9, in <module>
    load_entry_point('mysql-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/tokubackup.py", line 24, in all_procedure
  File "/opt/Python-3.3.2/lib/python3.3/runpy.py", line 178, in run_module
    fname, loader, pkg_name)
  File "/opt/Python-3.3.2/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 165, in <module>
AttributeError: 'CheckMySQLEnvironment' object has no attribute 'backupdir'
```

**Comment by ShahriyarR** [comment]
Fixed. Closing.
