### ISSUE TITLE
/opt/Python-3.3.2/bin/tokubackup --backup failed with PS 5.7; The 'INFORMATION_SCHEMA.GLOBAL_VARIABLES' feature is disabled

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#7]
The result:

```
/opt/Python-3.3.2/bin/tokubackup --backup
mysql: [Warning] Using a password on the command line interface can be insecure.
Something went wrong: 3167 (HY000): The 'INFORMATION_SCHEMA.GLOBAL_VARIABLES' feature is disabled; see the documentation for 'show_compatibility_56'
Something went wrong: 3167 (HY000): The 'INFORMATION_SCHEMA.GLOBAL_VARIABLES' feature is disabled; see the documentation for 'show_compatibility_56'
Traceback (most recent call last):
  File "/opt/Python-3.3.2/bin/tokubackup", line 9, in <module>
    load_entry_point('mysql-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/tokubackup.py", line 24, in all_procedure
  File "/opt/Python-3.3.2/lib/python3.3/runpy.py", line 178, in run_module
    fname, loader, pkg_name)
  File "/opt/Python-3.3.2/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autotokubackup-1.0-py3.3.egg/backup/backup_calculation.py", line 171, in <module>
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/utils/__init__.py", line 111, in start
    self.on_thread_start()
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/observers/inotify_c.py", line 187, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/watchdog-0.8.3-py3.3.egg/watchdog/observers/inotify_c.py", line 363, in _add_dir_watch
    raise OSError('Path is not a directory')
OSError: Path is not a directory
[root@tokubackup AutoTokuBackup]# ERROR 1231 (42000) at line 1: Variable 'tokudb_backup_dir' can't be set to the value of '/home/tokubackupdir'
```

**Comment by ShahriyarR** [comment]
It is clear from trace that, for PS 5.7 PERFORMANCE_SCHEMA.GLOBAL_VARIABLES should be used instead of INFORMATION_SCHEMA.GLOBAL_VARIABLES.
Also I have added a check if backup directory exists or not.
