### ISSUE TITLE
Run GUI tests on SauceLabs via bats

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-QA/percona-qa#88]
The following commands can be run from bats for gui tests
```
git clone https://github.com/Percona-QA/pmm-qa.git
cd pmm-qa
git pull

./start.sh config_saucelabs.js https://pmm:qwe1@IP
```

**Comment by ShahriyarR** [comment]
Failed with:

```
$ pmm-qa/start.sh config_saucelabs.js https://pmm:qwe1@10.10.11.50:8888
[10:39:18] E/configParser - Error code: 105
[10:39:18] E/configParser - Error message: failed loading configuration file config_saucelabs.js
[10:39:18] E/configParser - Error: Cannot find module '/home/shahriyar.rzaev/config_saucelabs.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ConfigParser.addFileConfig (/usr/lib/node_modules/protractor/built/configParser.js:123:26)
    at Object.initFn [as init] (/usr/lib/node_modules/protractor/built/launcher.js:92:22)
    at Object.<anonymous> (/usr/lib/node_modules/protractor/built/cli.js:205:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by ShahriyarR** [comment]
```
$ ./start.sh conf_sauce_labs.js https://pmm:qwe1@10.10.11.50:8888
[10:40:50] I/launcher - Running 14 instances of WebDriver
[10:40:51] I/testLogger - 
------------------------------------

[10:40:51] I/testLogger - [firefox 32 OS X 10.10 #01-3] PID: 19733
[firefox 32 OS X 10.10 #01-3] Specs: /home/shahriyar.rzaev/pmm-qa/specs/grafana_mongodb_mmvap.spec.js
[firefox 32 OS X 10.10 #01-3] 
[firefox 32 OS X 10.10 #01-3] [10:40:51] I/hosted - Using the selenium server at http://ondemand.saucelabs.com:80/wd/hub
[firefox 32 OS X 10.10 #01-3] 
[firefox 32 OS X 10.10 #01-3] /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27
[firefox 32 OS X 10.10 #01-3]     super(opt_error);
[firefox 32 OS X 10.10 #01-3]     ^
[firefox 32 OS X 10.10 #01-3] WebDriverError: Sauce Labs Authentication Error.
[firefox 32 OS X 10.10 #01-3] You used username 'None' and access key 'None' to authenticate, which are not valid Sauce Labs credentials.
[firefox 32 OS X 10.10 #01-3] 
[firefox 32 OS X 10.10 #01-3] The following desired capabilities were received:
[firefox 32 OS X 10.10 #01-3] {'browserName': 'firefox',
[firefox 32 OS X 10.10 #01-3]  'count': 1,
[firefox 32 OS X 10.10 #01-3]  'maxInstances': 25,
[firefox 32 OS X 10.10 #01-3]  'moz:firefoxOptions': {},
[firefox 32 OS X 10.10 #01-3]  'name': 'firefox-tests',
[firefox 32 OS X 10.10 #01-3]  'platform': 'OS X 10.10',
[firefox 32 OS X 10.10 #01-3]  'shardTestFiles': True,
[firefox 32 OS X 10.10 #01-3]  'version': '32'}
[firefox 32 OS X 10.10 #01-3]     at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
[firefox 32 OS X 10.10 #01-3]     at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:521:11)
[firefox 32 OS X 10.10 #01-3]     at doSend.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
[firefox 32 OS X 10.10 #01-3]     at process._tickCallback (internal/process/next_tick.js:109:7)
[firefox 32 OS X 10.10 #01-3] From: Task: WebDriver.createSession()
[firefox 32 OS X 10.10 #01-3]     at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
[firefox 32 OS X 10.10 #01-3]     at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/firefox/index.js:640:55)
[firefox 32 OS X 10.10 #01-3]     at createDriver (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
[firefox 32 OS X 10.10 #01-3]     at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:629:16)
[firefox 32 OS X 10.10 #01-3]     at Hosted.getNewDriver (/usr/lib/node_modules/protractor/lib/driverProviders/driverProvider.ts:60:29)
[firefox 32 OS X 10.10 #01-3]     at Runner.createBrowser (/usr/lib/node_modules/protractor/lib/runner.ts:225:39)
[firefox 32 OS X 10.10 #01-3]     at q.then.then (/usr/lib/node_modules/protractor/lib/runner.ts:391:27)
[firefox 32 OS X 10.10 #01-3]     at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
[firefox 32 OS X 10.10 #01-3]     at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
[firefox 32 OS X 10.10 #01-3]     at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)

[10:40:51] I/testLogger - 

[10:40:51] E/launcher - Runner process exited unexpectedly with error code: 1
[10:40:51] I/launcher - 13 instance(s) of WebDriver still running
```

**Comment by ShahriyarR** [comment]
New fail:
```
$ sudo ~/pmm-qa/start.sh ~/pmm-qa/config_saucelabs.js https://pmm:qwe1@10.10.11.50:8888
Report destination:   screenshots/pmm-test-report.html
[11:57:05] I/launcher - Running 6 instances of WebDriver
[11:57:06] I/testLogger - 
------------------------------------

[11:57:06] I/testLogger - [chrome 55 OS X 10.12 #11-0] PID: 28906
[chrome 55 OS X 10.12 #11-0] Specs: /home/shahriyar.rzaev/pmm-qa/specs/main_qan.spec.js
[chrome 55 OS X 10.12 #11-0] 
[chrome 55 OS X 10.12 #11-0] [11:57:05] I/local - Starting selenium standalone server...
[chrome 55 OS X 10.12 #11-0] [11:57:06] I/local - Selenium standalone server started at http://10.10.6.202:50296/wd/hub
[chrome 55 OS X 10.12 #11-0] 
[chrome 55 OS X 10.12 #11-0] /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27
[chrome 55 OS X 10.12 #11-0]     super(opt_error);
[chrome 55 OS X 10.12 #11-0]     ^
[chrome 55 OS X 10.12 #11-0] WebDriverError: No enum constant org.openqa.selenium.Platform.OS X 10.12
[chrome 55 OS X 10.12 #11-0]     at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
[chrome 55 OS X 10.12 #11-0]     at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
[chrome 55 OS X 10.12 #11-0]     at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
[chrome 55 OS X 10.12 #11-0]     at doSend.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
[chrome 55 OS X 10.12 #11-0]     at process._tickCallback (internal/process/next_tick.js:109:7)
[chrome 55 OS X 10.12 #11-0] From: Task: WebDriver.createSession()
[chrome 55 OS X 10.12 #11-0]     at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
[chrome 55 OS X 10.12 #11-0]     at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
[chrome 55 OS X 10.12 #11-0]     at createDriver (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
[chrome 55 OS X 10.12 #11-0]     at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:623:16)
[chrome 55 OS X 10.12 #11-0]     at Local.getNewDriver (/usr/lib/node_modules/protractor/lib/driverProviders/driverProvider.ts:60:29)
[chrome 55 OS X 10.12 #11-0]     at Runner.createBrowser (/usr/lib/node_modules/protractor/lib/runner.ts:225:39)
[chrome 55 OS X 10.12 #11-0]     at q.then.then (/usr/lib/node_modules/protractor/lib/runner.ts:391:27)
[chrome 55 OS X 10.12 #11-0]     at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
[chrome 55 OS X 10.12 #11-0]     at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
[chrome 55 OS X 10.12 #11-0]     at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
```

**Comment by ShahriyarR** [comment]
As discussed with team and also with @mykola.
This feature is going to be implemented directly in Jenkins.
Closing.
